name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd task-app-backend
          npm install
          npm run build

      - name: Test
        run: |
          cd task-app-backend
          npm run test

      - name: Deploy
        run: |
          cd task-app-deployment
          # deployment steps here